<?php

namespace App\Http\Controllers\Api\V1\Team;

use App\Http\Controllers\Controller;
use App\Http\Resources\PayrollEntryResource;
use App\Models\PayrollEntry;
use App\Models\Task;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Own payslips for every internal role (the /team "Payslips" page). Scoped hard
 * to the token's own user id. Returns two things in one round-trip:
 *   - `payslips`       the member's own payroll entries (paginated), each with
 *                      its allowance/extras/gross breakdown + linked task extras.
 *   - `pending_extras` their completed-with-pay tasks (payment_pending) not yet
 *                      on any payslip — shown separately so the member can see
 *                      money owed that a future payslip will settle.
 * Read-only: entries are generated by the founder in the cockpit.
 */
class PayrollController extends Controller
{
    public function index(Request $request): JsonResponse
    {
        $userId = $request->user()->id;

        $entries = PayrollEntry::where('user_id', $userId)
            ->with('tasks')
            ->latest()
            ->latest('id')
            ->paginate(20);

        // Unlinked, still-pending task extras — money owed but not yet on a slip.
        $pending = Task::where('assignee_id', $userId)
            ->where('status', 'payment_pending')
            ->whereNull('payroll_entry_id')
            ->whereNotNull('pay_amount_myr')
            ->orderByDesc('completed_at')
            ->get();

        return response()->json([
            'payslips' => PayrollEntryResource::collection($entries)->response($request)->getData(true),
            'pending_extras' => [
                'tasks' => $pending->map(fn (Task $task) => [
                    'id' => $task->id,
                    'title' => $task->title,
                    'pay_amount_myr' => $task->pay_amount_myr,
                    'completed_at' => $task->completed_at?->toISOString(),
                ])->values(),
                'total_myr' => (int) $pending->sum('pay_amount_myr'),
            ],
        ]);
    }
}
